
platform :ios, "8.0"

target 'MYUtils' do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'MJExtension', '~> 3.0.13'
    pod 'IconFont', '~> 1.0.2'
    pod 'CTMediator'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'Masonry', '~> 1.0.2'
    pod 'MYKit', '~> 1.0.4'
    pod 'TYPagerController' , '~> 2.0.1'
    pod 'CYLTabBarController', '~> 1.13.1'
    pod 'DACircularProgress', '~> 2.3.1'
    pod 'WebViewJavascriptBridge', '~> 6.0.2'
    pod 'ZYKeyboardUtil', '~> 1.0.7'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'IGLDropDownMenu', '~> 1.6.2'
    pod 'YYKit', '1.0.9'
    pod 'pop', '~> 1.0.10'
end  
