
platform :ios, "8.0"

target 'MYUtils' do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'MJExtension', '~> 3.0.13'
    pod 'IconFont', '~> 1.0.2'
    pod 'CTMediator'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'Masonry', '~> 1.0.2'
    
    pod 'TYPagerController' , '~> 2.0.1'
    
    pod 'CYLTabBarController', '~> 1.13.1'
    
end  
